version: "3.8"
services:
  mssql-master:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-master
    hostname: mssql-master
    env_file: .env
    restart: always
    shm_size: '2gb'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    tmpfs:
      - /var/opt/mssql
    stop_grace_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/1433"]
      interval: 5s
      retries: 10

